{% set name = "ocamlbuild" %}
{% set version = "0.14.2" %}
{% set sha256 = "62d2dab6037794c702a83ac584a7066d018cf1645370d1f3d5764c2b458791b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ocaml/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - ocaml
  run:
    - ocaml

test:
  commands:
    - ocamlbuild -version
    - ocamlbuild.native -version

about:
  home: https://ocaml.org/
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: OCamlbuild is a generic build tool, that has built-in rules for building OCaml library and programs.

  # The remaining entries in this section are optional, but recommended
  description: |
    OCaml is an implementation of the ML language, based on the Caml Light
    dialect extended with a complete class-based object system and a powerful
    module system in the style of Standard ML.

    OCamlbuild was distributed as part of the OCaml distribution for OCaml
    versions between 3.10.0 and 4.02.3. Starting from OCaml 4.03, it is now
    released separately (with its own version numbering).

    You should refer to the OCambuild manual for more informations on how to
    use ocamlbuild.
  doc_url: https://github.com/ocaml/ocamlbuild/blob/master/manual/manual.adoc
  dev_url: https://github.com/ocaml/ocamlbuild

extra:
  recipe-maintainers:
    - peterjc
