travis:
  secure:
    BINSTAR_TOKEN: J6EG4e1lu35sSvwPgWz7xioXv4AlX9905mE/lOnJ7yCPvSa3gid98KH5I4uRTLKus9WnA99rOQO74D+qDci3q6tUFfWnUxcnbdD0EUDPqbyLrIeu2o+9J9gBsCsPtM4VW2jiD0rR0aX3RT4Bu7d7xqWeQFKm3k5RUhOlqovGb6GMHVpMYWA+7kQisljvxjWg5iIFFdwcxejhIxKpjX5yFCXM1YXrLXmeJK6DogzgypqrxAMfHQmUhUDZu0AABWlTHUGbLpf/Ycn/rhAbv1S6ojkh6MKuO9Jjv8pT+BEjdrJMKZo9qH48tjtr3o4bWJCuW7R4M9NkWns8M8qKfhVQdS8nAPRk8LDJHlfivOBJGo7vx0j1IfrSlGq5G9Xf0WmGHp+KfJac/iBZoPESlAomkL95yIpdOxOdFD+hv2GBmdn9dv9WhovkiXSEFKetcrzHUq2k7N1zmEQLpYvkfK5nI8+Tc9NIAjyj5F9/6Z+go9G8W4zcu2a0NmsjHCBbHbd8gsH4Hgp3wg2y/ixfRty39qWdiByVeD2dARpG5iVSySmNfOgnW4ND+676azJEhDQptXaIDtcfy25K8uwzv4doE2/AcpZU+t6Yw+O7CG1GIlQHAIfgukanDqiyOLNhJEh9/VbLiYXdu6qOagIZW7Gm0QsO2zmNhqFYQfx8askk/qo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
