travis:
  secure:
    BINSTAR_TOKEN: qh7CR2ivagsgUOzuD1DVnQk03nHCqLMJGBH3UlJqTFqO+14ThJWyqxZvZAUNn7wfDIQZx6D85AbhayLlyRItPrzzKwNB5QHP5xXbySdr1GhVUcU0T1oHo89Qr0ilSdAEwFvUesdur+DBKnT25uPJFEUjwTrZC1mqEgtabcm57t1Xph7a/fWmwq0Po6FJRT6zb/W1nMlMkux2eXNrXxrQFAZ/QMnOzYcfGqdSvHSaJW0xsK3zWrctFpoTT2IQjQfTMoh6BSDCvReeot8A2cfdIITdvhB9d/qfmUwCS1SDrmASD0lCBwKzBFTudAuPbyEaNhfreepUb90DympogCJH/VW4clC5Y3Jqc8jmJGcQmGMzmJ6T0+a/14USBJEPJ0UdLc8z5C76sbW4+24m0+Wnlq5qJFLsr1ql5dTaH5Tv0osqPCCfDSCMzaEgZzuB8Xye3MQlIIiByJYp3ymgHcoqMdb/H9rXAaitNd56wCDaTMohbXtZvXZpBGikQDg/kjk5tE3XlJ4GUN5S9MA8ct2YYrmXLymlHJhQnor/yJslIpWudofKqZACMRlBL+pCRhla/ajyGaha5W+clX9OlOi24CtQSIIYCzUPqA3l8LmgsCSuRe4yjMe5ThRs11oyhhZKEv3nx8Sb50fv5A/QRcc2LwO/EG4HkZoJkiQY3FW/T1M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
