travis:
  secure:
    BINSTAR_TOKEN: fkdFWwvsoY49TKPk0RpfSIK82BJxw5GeSFLJa873l09nQFCEdWRTqtyld4tpLV421WQ3nBOvyM5ytUA6LPPYonMOqMNwYyRktAau/KRWbeEgKlzZljWQ0ZlOHOtRais/9J3Ji4koIKsDqBvwqOcJ+m3eYBJure5Meb4ZO1AF/NtM4ts0rcKW9VtRYrxgZ8CVAcgXgxauw6BtQpa7lxnNoWgmjszbkSVZx4WBPNscG3pSsPaM2grykHZczGuYLAWTrKIGcXFl6RL0/ReRf/yNVvlZEFu87PZ/OIDRUl4Z6ylILS9AxTFIZotoNafyhhCHCL6K/k2ARPR6nYRW32ChFlLDw6QIps7X/9lScbkGZD9e6k9x2VkwVMjIRGoqVKtQi4gvIfzEpjfWPjcp7LLjd7d64PfOxZ5o+yB6eIRRws2HoQTwD1F141JSTZg65pJP6ZMEOozhcSMDuP7iVaNgPMk/Wi7soHgFs3ryPQIXbWAfQOO/JLk7HTYqmWrjY4Tf7ja/By/9mYnnESlAgAKHsMkXW4OuHxbtLCNDTXFh6QMQXczwfw7UB+QilcNsfKCnMyD7mXh1P3t4wbsbPyrT4gwfSRgRS7vMqNmoKg6h/vnk8uTulo5uW5VKVL8MuNIwt8idcP37djXUKVM63SdWVfLc5Q5PdgbzlUE5jFOsV7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
