travis:
  secure:
    BINSTAR_TOKEN: cl3M5mPPn1o4NHkSWAZUyqmEhnU7rf5wxbqVOgxDzJtX9a6J4yJHw18KmpsIFZCMni0Qsr1daBKcuO0GQs2s3nXMLSHx/v1eJDx/DHcwWjdG14uSZd0Zn/5U++GnQj9ODsBUOmo6jAhEAXr37E4oeDn9aSC7C/niStyz5h1xrEoYh2BgOfu4pjl88ItpgtdrYabNOeGU9gdVU+h3yqoORA4fs/rC4ONBJnmPpRZxXdwnCyZAzOd+fchfkYznK7ZIZ3xo1/eqzb5NDTKCXnIHeLrNASxFFD2gjFws/sC3IX63GqHsic5lCTmnj+h5jpbUk6wODsxAhZ9/BON1psDZLG8sfjvoztq/QSWP4y7AeWmQd1sQKk2Akhgb/V1T4iqLgmDsf+aN7nwh8vpYHo0wBIT1mjIOtBGpjCwuw6jIk7UQbfdBQ6bne9NC5t6Vka3ZSf6+Nj1SImHPOlJx9raKJ9AnwPgBPYfwMZ5c1QfFfWmc7tWB9rsaTyfwhaJNwPTOdDbiZjy16wnXjHpqnYVFo25c7QWEMdbDtaYxo9jjnDXhCePf3tW3UmGKP+gV4ohZIrTzjjhQaje7mQj7L2PKoUgYi9rgNEuLh34c/JpEAwSeaevkk3sNRIP8EXVrh28j5Qwp8J4FJEhcJZ1jPx+eztc93uIZeD3DQbzVQ4ZbYf0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
